
services:

  db:
    image: mysql:8.0.40
    restart: always
    container_name: Mysql
    volumes:
      - C:/containers/database/pontoeletronico/mysql:/app/data/mysql
    env_file:
      - ./.env
    ports:
      - 3030:3306
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    container_name: backend
    volumes:
      - C:/containers/backend/pontoeletronico/python:/app/data/python
    env_file:
      - ./.env
    ports:
      - 8888:8080
    depends_on:
      - db
  

    
 
  