"""excluindo a tabela registros_de_pontos

Revision ID: 1cd80b44a253
Revises: f8e60f2c55c4
Create Date: 2025-09-15 02:04:28.404183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd80b44a253'
down_revision: Union[str, None] = 'f8e60f2c55c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_de_pontos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_de_pontos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_funcionario', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=19), nullable=False),
    sa.Column('cpf_funcionario', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
