"""Reconfigurando as tabelas

Revision ID: 1dbceee6050c
Revises: c0c03ca5d271
Create Date: 2025-01-26 19:30:54.441513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1dbceee6050c'
down_revision: Union[str, None] = 'c0c03ca5d271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('funcionarios_ibfk_2', 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'nome_empresa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('nome_empresa', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('funcionarios_ibfk_2', 'funcionarios', 'empresas', ['nome_empresa'], ['nome'])
    # ### end Alembic commands ###
