"""criando a tabela registros

Revision ID: 2a301567800f
Revises: 1cd80b44a253
Create Date: 2025-09-15 02:06:00.607238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a301567800f'
down_revision: Union[str, None] = '1cd80b44a253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('nsr', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_funcionario', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('Entrada', 'Saída', 'Início do Intervalo', 'Fim do Intervalo'), nullable=False),
    sa.ForeignKeyConstraint(['cpf_funcionario'], ['funcionarios.cpf'], ),
    sa.PrimaryKeyConstraint('nsr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
