"""Reconfigurando as tabelas

Revision ID: 41a6aaef26b0
Revises: 8caa97ae7b7d
Create Date: 2025-01-26 16:31:40.887083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a6aaef26b0'
down_revision: Union[str, None] = '8caa97ae7b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
