"""Adiciona colunas de user e senha na tabela relogios

Revision ID: 44d8b630f740
Revises: 306bfb93c279
Create Date: 2025-08-29 08:59:59.742211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d8b630f740'
down_revision: Union[str, None] = '306bfb93c279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relogios', sa.Column('user', sa.String(), nullable=False))
    op.add_column('relogios', sa.Column('senha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relogios', 'senha')
    op.drop_column('relogios', 'user')
    # ### end Alembic commands ###
