"""Iniciando a tabela de registros de pontos

Revision ID: 49c4eae68538
Revises: a5cfaa81aa11
Create Date: 2025-01-29 20:49:13.351414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49c4eae68538'
down_revision: Union[str, None] = 'a5cfaa81aa11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_de_pontos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('Entrada', 'Saída', 'Início do Intervalo', 'Fim do Intervalo'), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('funcionarios', 'empresa_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'empresa_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('registros_de_pontos')
    # ### end Alembic commands ###
