"""Faz mudanças a tabela de registros, recriando

Revision ID: 4e7cbace0419
Revises: 4eb5f28b8048
Create Date: 2025-10-06 02:47:56.075215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7cbace0419'
down_revision: Union[str, None] = '4eb5f28b8048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('nsr', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_funcionario', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('Entrada', 'Saída'), nullable=False),
    sa.ForeignKeyConstraint(['cpf_funcionario'], ['funcionarios.cpf'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('nsr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
