"""Faz mudanças a tabela de registros, excluindo

Revision ID: 4eb5f28b8048
Revises: 7487f51985f1
Create Date: 2025-10-06 02:47:28.358250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5f28b8048'
down_revision: Union[str, None] = '7487f51985f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('nsr', sa.INTEGER(), nullable=False),
    sa.Column('cpf_funcionario', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=19), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cpf_funcionario'], ['funcionarios.cpf'], ),
    sa.PrimaryKeyConstraint('nsr')
    )
    # ### end Alembic commands ###
