"""Faz mudanças a tabela de registros

Revision ID: 7487f51985f1
Revises: 2a301567800f
Create Date: 2025-10-06 02:44:32.805700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7487f51985f1'
down_revision: Union[str, None] = '2a301567800f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.alter_column('registros', 'tipo',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('Entrada', 'Saída'),
               existing_nullable=False)
    op.create_foreign_key(None, 'registros', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registros', type_='foreignkey')
    op.alter_column('registros', 'tipo',
               existing_type=sa.Enum('Entrada', 'Saída'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.drop_column('registros', 'empresa_id')
    # ### end Alembic commands ###
