"""Reconfigurando as tabelas

Revision ID: a5cfaa81aa11
Revises: 1dbceee6050c
Create Date: 2025-01-27 20:02:47.448608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cfaa81aa11'
down_revision: Union[str, None] = '1dbceee6050c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
