"""Add Funcionarios Table

Revision ID: be1ab144b489
Revises: 09313989e6e3
Create Date: 2025-01-16 19:04:50.395686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1ab144b489'
down_revision: Union[str, None] = '09313989e6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=75), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('pis', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('data_adm', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('pis')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
