"""Reconfigurando as tabelas

Revision ID: c0c03ca5d271
Revises: 41a6aaef26b0
Create Date: 2025-01-26 16:39:52.085766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c03ca5d271'
down_revision: Union[str, None] = '41a6aaef26b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funcionarios', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'funcionarios', 'empresas', ['nome_empresa'], ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'empresa_id')
    # ### end Alembic commands ###
