"""Add Empresas Table

Revision ID: c999c8f7cfe1
Revises: be1ab144b489
Create Date: 2025-01-26 16:12:03.345977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c999c8f7cfe1'
down_revision: Union[str, None] = 'be1ab144b489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('nome_empresa', sa.String(length=100), nullable=True))
    op.drop_column('funcionarios', 'empresa')
    op.drop_column('funcionarios', 'data_adm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('data_adm', sa.DATE(), nullable=False))
    op.add_column('funcionarios', sa.Column('empresa', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('funcionarios', 'nome_empresa')
    # ### end Alembic commands ###
