"""migrando para o postgres

Revision ID: d7b24c2a758b
Revises: 
Create Date: 2025-10-08 22:30:08.476358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b24c2a758b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('pis', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('pis')
    )
    op.create_table('relogios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('porta', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('porta >= 0 AND porta <= 65535', name='porta_range'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('registros',
    sa.Column('nsr', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_funcionario', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('relogio_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('Entrada', 'Saída', name='tipo_registro'), nullable=False),
    sa.ForeignKeyConstraint(['cpf_funcionario'], ['funcionarios.cpf'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['relogio_id'], ['relogios.id'], ),
    sa.PrimaryKeyConstraint('nsr'),
    sa.UniqueConstraint('relogio_id', 'nsr', name='unique_device_nsr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('relogios')
    op.drop_table('funcionarios')
    op.drop_table('users')
    op.drop_table('empresas')
    # ### end Alembic commands ###
