"""alteração na tabela registros_de_pontos

Revision ID: f8e60f2c55c4
Revises: 44d8b630f740
Create Date: 2025-09-15 01:36:02.238296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e60f2c55c4'
down_revision: Union[str, None] = '44d8b630f740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_de_pontos', sa.Column('cpf_funcionario', sa.String(), nullable=False))
    with op.batch_alter_table("registros_de_pontos", schema=None) as batch_op:
        # aqui você remove a coluna antiga que não quer mais
        batch_op.drop_column("id_funcionario")  
    op.create_foreign_key(None, 'registros_de_pontos', 'funcionarios', ['cpf_funcionario'], ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registros_de_pontos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_funcionario", sa.String(), nullable=True))
    op.create_foreign_key(None, 'registros_de_pontos', 'funcionarios', ['id_funcionario'], ['id'])
    op.drop_column('registros_de_pontos', 'cpf_funcionario')
    # ### end Alembic commands ###
