"""exclui a coluna email da tabela users

Revision ID: fd068a98380d
Revises: 4e7cbace0419
Create Date: 2025-10-08 05:06:31.318834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd068a98380d'
down_revision: Union[str, None] = '4e7cbace0419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
